# =============================================================================
# Filename:     .travis.yml
# Maintainer:   Stephen Davis <https://github.com/webdavis>
# License:      GPLv3
# Repository:   ansible-vagrant
# Last Change:  Saturday 2017-04-15 09:37:56 MST
# Description:  Travis CI will build the required tools for this role.
# =============================================================================

language: python
python:
    - 2.7

# Travis CI defaults to Python 2.7 so specifying the key isn't necessary in this use
# case.

# We need sudo access to test this role so use a full Virtual Machine such as one in a
# Vagrant machine instead of a container such as Docker or Ansible.
sudo: required

# Install Ansible.
addons:
    apt:
        packages:
            - python-pip

install:
    # Install the required Python libraries.
    - pip install -r tests/requirements.txt

    # Check Ansible version.
    - ansible --version
