---
dependencies: []

galaxy_info:
  author: webdavis
  description: An Ansible role for installing Vim.
  license: "license (GPLv3)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Fedora
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
    - name: FreeBSD
      versions:
      - 10.2
  galaxy_tags:
    - vim
    - installer
    - linux
    - macos

  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
